### ISSUE TITLE
Feature Request - Add in help for command options

### ISSUE THREAD

**Issue by norman-abramovitz** [jhunt/boss#5]
Do you have any issues adding in help for command options?  I would do it the same way as global options by adding functions for each command that has additional options.   There is no way to know these options exist unless you look at the code.

I was thinking the output would be like

```
Usage: boss [options] list [-l]

Command Options:

  (these options must go after the command)

  -l, --long      display additonal details about service instances

Options:

  (these can go anywhere on the command line, by the way...)


We could be terser by using this format style.
```
Usage: boss [options] catalog [command options]

Command Options:
 
 -l, --long      display additonal details about catalog plans

Options:

**Comment by jhunt** [comment]
Fixed in #7
